FROM nginx:alpine
COPY nginx.conf       /etc/nginx/conf.d/default.conf
COPY dashboard.html   /usr/share/nginx/html/
COPY directorio.html  /usr/share/nginx/html/
COPY catalogo.html    /usr/share/nginx/html/
COPY gestion.html     /usr/share/nginx/html/
COPY disponibilidad.html /usr/share/nginx/html/
COPY login.html        /usr/share/nginx/html/
COPY nav.js           /usr/share/nginx/html/
